# Generated by Django 5.2.8 on 2025-12-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone (Main)'),
        ),
    ]
