# Generated by Django 5.2.8 on 2025-12-03 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reconfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for', models.DateField()),
                ('date_sent', models.DateTimeField(blank=True, null=True)),
                ('assignees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flight_number', models.CharField(max_length=10)),
                ('opening_counters', models.TimeField(blank=True, null=True)),
                ('closing_counters', models.TimeField(blank=True, null=True)),
                ('boarding_bus', models.TimeField(blank=True, null=True)),
                ('arrival_at_aircraft', models.TimeField(blank=True, null=True)),
                ('supervisor_closed', models.BooleanField(default=False)),
                ('aircraft_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.aircraft')),
                ('counters_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_flights', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_flights', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'flight_number')},
            },
        ),
    ]
