# Generated by Django 5.2.8 on 2025-12-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='aircraft_reg',
            new_name='aircraft',
        ),
    ]
