# Generated by Django 5.2.8 on 2025-12-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_assigned_to_alter_flight_dispatched_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='supervisor_closed',
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Dispatched')], default=0),
        ),
    ]
