# Generated by Django 5.2.8 on 2025-12-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_flight_supervisor_closed_flight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconfirmation',
            name='date_for',
            field=models.DateField(unique=True),
        ),
    ]
