# Generated by Django 5.2.8 on 2025-12-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
