# Generated by Django 5.2.8 on 2026-02-25 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_booking_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconfirmation',
            name='assignees',
            field=models.ManyToManyField(related_name='reconfirmations', to=settings.AUTH_USER_MODEL),
        ),
    ]
