# Generated by Django 5.2.8 on 2026-02-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_alter_reconfirmation_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='counters_not_applicable',
            field=models.BooleanField(default=False),
        ),
    ]
